services:
  - type: web
    name: be-todo
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_HOST
        value: dpg-d6ra1ekhg0os73a51q3g-a.singapore-postgres.render.com
      - key: DB_USER
        value: be_todo_db_1hkc_user
      - key: DB_PASSWORD
        value: Ev0O3Py4nsLVZdEsJGlgKi4RYe1E3MFy
      - key: DB_NAME
        value: be_todo_db_1hkc
      - key: PORT
        value: 5000

  - type: web
    name: fe-todo
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://backend-todo-dg3a.onrender.com